const BAD_REQUEST_CODE = 400;
const INTERNAL_ERROR_CODE = 500;
const SUCCESS_CODE = 200;
const UNAUTHORIZED_CODE = 401;
const FORBIDDEN_CODE = 403;
const NOT_FOUND_CODE = 404;
const CONFLICT_CODE = 409;
const UNPROCESSABLE_ENTITY_CODE = 422;
const CREATED_CODE = 201;

const DATA_NOT_PROVIDED = 'Data not provided';
const INVALID_EMAIL = 'Invalid email';
const INVALID_USERNAME = 'Invalid username';
const INVALID_PASSWORD = 'Invalid password';
const INTERNAL_ERROR = 'Internal error';
const INVALID_TOKEN = 'Token is invalid';
const CREATED = 'Created successfully';
const USER_ALREADY_EXISTS = 'User already exists';

export {
  BAD_REQUEST_CODE,
  INTERNAL_ERROR_CODE,
  SUCCESS_CODE,
  UNAUTHORIZED_CODE,
  FORBIDDEN_CODE,
  NOT_FOUND_CODE,
  CONFLICT_CODE,
  UNPROCESSABLE_ENTITY_CODE,
  DATA_NOT_PROVIDED,
  INVALID_EMAIL,
  INVALID_USERNAME,
  INVALID_PASSWORD,
  INTERNAL_ERROR,
  CREATED,
  INVALID_TOKEN,
  CREATED_CODE,
  USER_ALREADY_EXISTS,
};
